- name: Copy the repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongod-org
    state: present

- name: update listner in confif
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start mongod services
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    state: restarted
