#- name: play level variables
#  hosts: all
#  vars:
#     URL: play.sample.com
#  tasks:
#    - name: variables in task1
#      ansible.builtin.debug:
#        msg: acess variable in task1 = {{URL}}
#
#    - name: Variables in task2
#      ansible.builtin.debug:
#        msg: access variable in task2 = {{URL}}

#Declare variables in play level can be accessed by by every tasks

#- name: variables from file
#  hosts: all
#  vars_files:
#      - Variables-file.yml
#  tasks:
#     - name: variables in task1
#       ansible.builtin.debug:
#           msg: URL = {{URL}}

#variables accessed from files

#- name: variables from task level
#  hosts: all
#  tasks:
#     - name: variables in task1
#       ansible.builtin.debug:
#          msg: URL = {{URL}}
#       vars:
#         URL: task.example.com
#task levael variables
- name: variables from task level
  hosts: all
  tasks:
     - name: variables in task1
       ansible.builtin.debug:
          msg: URL = {{URL}}
#Iventroy level variables
