- name: play1
  hosts: all
  tasks:
     - name: print task1
       ansible.builtin.debug:
           msg: "print task1"

     - name: print task2
       ansible.builtin.debug:
         msg: "print task2"

- name: play2
  hosts: all


