- name: demo on loops
  hosts: localhost
  vars:
    fruits: [ 'mango' 'apple' ]

    - name: print fruits
      ansible.builtin.debug:
        msg: "fruits = {{items}}
      loops:
          - mango
          - apple