- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: Download and Extract {{COMPONENT}} code
  include_role:
    name: common
    tasks_from: download

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
