- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: Download and Extract code
  include_role:
    name: common
    tasks_from: download
