- name: copy sql repos
  ansible.builtin.copy:
    name: sql-repo
    src: mysql.repos
    dest: /etc/yum.repos.d/mysql.repo

- name: remove mariadb-libs
  ansible.builtin.yum:
    name: marisdb-libs
    state: absent

- name: Install MySql
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: Start MySql services
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes


