- name: copy sql repos
  ansible.builtin.copy:
    src: mysql.repos
    dest: /etc/yum.repos.d/mysql.repo

- name: remove mariadb-libs
  ansible.builtin.yum:
    name: marisdb-libs
    state: absent

- name: Install MySql
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: Start MySql services
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Default root password
  ansible.builtin.shell:  grep 'temporary password'  /var/log/mysqld.log | awk '{print $NF}'
  register: DEFAULT_PASSWORD

- name: check newpassword working
  ansible.builtin.shell: echo 'show databases;' | mysql -uroot -p"{{NEW_PASSWORD}}"
  register: CHECK_NEW_PASSWORD
  ignore_errors: yes

- name: print
  ansible.builtin.debug:
    msg: "{{CHECK_NEW_PASSWORD}}"

- name: password reset sql
  ansible.builtin.template:
    src: pass.sql
    dest: /tmp/pass.sql
  when: CHECK_NEW_PASSWORD.failed

- name: reset apssword
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD.stdout}}" </tmp/pass.sql
  when: CHECK_NEW_PASSWORD.failed


- name: Download and Extract {{COMPONENT}} code
  include_role:
      name: common
      tasks_from: download

- name: load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{NEW_PASSWORD}}"



