- name: Install Nodejs
  ansible.builtin.yum:
      name: [ "nodejs", "make", "gcc-c++" ]
      state: present

- name: Download and Extract {{COMPONENT}} code
  include_role:
    name: common
    tasks_from: download

- name: remove old content
  ansible.builtin.file:
    path: home/roboshop
    state: absent

- name: copy the content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: true
  become_user: roboshop

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/roboshop/catalogue

