- name: Install Nodejs
  ansible.builtin.yum:
      name: [  "make", "gcc-c++" ]
      state: present

- name: "Install nodejs"
  apt:
    update_cache: yes
    ame: nodejs
    state: present

- name: "Install NPM-distributed command-line tools"
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
          - firebase-tools

- name: Download and Extract {{COMPONENT}} code
  include_role:
    name: common
    tasks_from: download

- name: remove old content
  ansible.builtin.file:
    path: home/roboshop
    state: absent

- name: copy the content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: true
  become_user: roboshop

- name: Install node.js dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop
