- name: Install Maven
  ansible.builtin.yum:
     name: mave
     state: present

- name: Download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  APP_LOCATION: "/home/roboshop/{{COMPONENT}}"



